IK-27: базовая механика игры
LemonGrace/it-kotiki pull request #10
Opened 2024-03-24 15:22 UTC by Aftors

### Какую задачу решаем
IK-27: Базовая механика игры 

1. Луп игры через requestAnimationFrame
2. Обработка событий keyboard
3. Рисование объектов
4. Обнаружение коллизии
5. базовая анимация

### Скриншоты/видяшка (если есть)

![Снимок экрана 2024-03-24 в 18 20 31](https://github.com/LemonGrace/it-kotiki/assets/76446447/9e93e64e-6fe6-4c7a-82e2-783f2790c26b)

### TBD (если есть)

2024-03-24 16:31 UTC, auddax approved these changes

2024-03-24 18:11 UTC, khedamir approved these changes

2024-03-24 18:21 UTC, LemonGrace requested changes

2024-03-24 18:21 UTC, LemonGrace commented on packages/client/src/core/models/models.ts
> +export type CenterType = {
А чем отличаются типы `CenterType `, `PositionType` и `IPath`? Можно ли их объединить в один `ICoordinateType`?

2024-03-24 18:21 UTC, LemonGrace commented on packages/client/src/core/build.ts
> +		const path = this.path[this.pointIndex];
Можно упростить вложенность через
```
if (!path) {
return;
}
```

2024-03-24 18:21 UTC, LemonGrace commented on packages/client/src/core/build.ts
> +		if (this.target !== null) {
Тут аналогично комментарию выше

2024-03-24 18:21 UTC, LemonGrace commented on packages/client/src/core/core.ts
> +				player.position.x - x + player.width >= boundary.position.x &&
Может это вынести в отдельный метод с декомпозицией?
```
public GetIsStop(player, boundary, offsetX, offsetY): boolean {
const playerPositionX = player.position.x;
const boundaryPositionX = boundary.position.x;

if (playerPositionX - x  + player.width < boundaryPositionX) {
    return false;
}
....
}

```

2024-03-24 18:39 UTC, Aftors commented on packages/client/src/core/core.ts
> +				player.position.x - x + player.width >= boundary.position.x &&
Не имеет смысла, так как используется только в в конкретной функции

2024-03-24 18:39 UTC, Aftors commented on packages/client/src/core/build.ts
> +		if (this.target !== null) {
исправил

2024-03-24 18:39 UTC, Aftors commented on packages/client/src/core/build.ts
> +		const path = this.path[this.pointIndex];
исправил

2024-03-24 18:39 UTC, Aftors commented on packages/client/src/core/models/models.ts
> +export type CenterType = {
Вынес в один тип

2024-03-24 19:23 UTC, LemonGrace approved these changes

2024-03-25 08:50 UTC, kate-lozovaya requested changes
Оставила комментарии. Из основного: 
- разбей на файлики все классы
- вынеси числа в константы, потому что при добавлении картинок может понадобиться поменять эти числа, а это сделать будет сложно
- доработай функцию `distanceHypot`

Ответь на комментарии и призывай к ревью

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/utils/hypot.ts
> +	const xDifference = a.center.x - b.center.x + checkX;
[Исправление]
Замени `any` на тип, который тут должен быть. У `any` не может быть `.center.x`.
Здесь можно определить только нужные поля, то есть `center` с `x` и `y`

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/events.ts
> +export const addEventKeys = (name: string, keys: IKeys, flag: boolean) => {
[Вопрос]
Тут осознано мутируется `keys`?

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/build.ts
> +	height = 40;
[Исправление]
Лучше чтобы каждый класс хранился в своем файлике, раздели их, пожалуйста. Это помогает в будущем проще отслеживать изменения и создает порядок в коде. 

И в классах используются числа, которые тоже стоит вынести, чтобы было одно место, где можно поменять при необходимости константы.

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/core.ts
> +	canvas.width = 1408;
[Исправление]
Стоит вынести числа в константы

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/core.ts
> +			const distance = Math.hypot(xDifference, yDifference);
[Исправление]
Это похоже на функцию `distanceHypot`. Не стоит дублировать код, воспользуйся тут ей

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/utils/hypot.ts
> +	const xDifference = a.center.x - b.center.x + checkX;
Но использование переменных с `center` не универсальное. Думаю, тут как `a` и `b` сразу стоит брать точки `(x, y)`
Тогда будет тип `type Point = { x: number; y: number }`

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/core.ts
> +		}
[Предложение]
Выглядит как дублирование кода. Если ввести переменные для направления, то можно будет избежать его.
```
const verticalDirection = keys.w.pressed ? -1 : (keys.s.pressed ? 1 : 0);
const horizontalDirection = keys.a.pressed ? -1 (keys.d.pressed ? 1 : 0);

if (!moving(horizontalDirection * 5, verticalDirection * 5)) {
    player.center.x += horizontalDirection * player.velocity;
    player.position.x += verticalDirection * player.velocity;
}
```

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/core.ts
> +			if (!moving(-5, 0)) {
[Вопрос]
Кажется, для `a` и `d` перепутан знак в `moving`. проверь, пожалуйста

2024-03-25 08:50 UTC, kate-lozovaya commented on packages/client/src/core/events.ts
> +			}
[Предложение]
Можно сократить запись, если сделать маппер для кнопок
```ts
const keyMapping = {
    'w': 'ц',
    'a': 'ф',
    's': 'ы',
    'd': 'в'
};
```
Тогда можно будет здесь оставить одно условие в цикле 
```suggestion
Object.keys(keyMapping).forEach((key) => {
	if (e.key === key || e.key === keyMapping[key]) {
		keys[key].pressed = flag;
        }
});
```

Нельзя сказать, что такая запись лучше, потому что расширяться эта функция не будет. Просто как вариант, который можно рассмотреть

2024-03-25 16:29 UTC, Aftors commented on packages/client/src/core/utils/hypot.ts
> +	const xDifference = a.center.x - b.center.x + checkX;
Изменил, сделал более универсальным.

2024-03-25 16:30 UTC, Aftors commented on packages/client/src/core/build.ts
> +	height = 40;
Вынес классы, сформировал файл констант.

2024-03-25 16:31 UTC, Aftors commented on packages/client/src/core/core.ts
> +	canvas.width = 1408;
Сделано

2024-03-25 16:31 UTC, Aftors commented on packages/client/src/core/core.ts
> +			const distance = Math.hypot(xDifference, yDifference);
Именно так, забыл поправить.

2024-03-25 16:33 UTC, Aftors commented on packages/client/src/core/core.ts
> +		}
Хорошая идея, но разделил на две части, так как блокируется диагональное движение, при контакте одной из осей.

2024-03-25 16:35 UTC, Aftors commented on packages/client/src/core/core.ts
> +			if (!moving(-5, 0)) {
Этих условий теперь нет.

2024-03-25 16:35 UTC, Aftors commented on packages/client/src/core/events.ts
> +			}
Отличная идея, не пришло в голову.

2024-03-25 16:52 UTC, kate-lozovaya approved these changes
👍🏻

2024-03-25 17:13 UTC, merged