IK-22: Сверстать экран с началом игры
LemonGrace/it-kotiki pull request #12
Opened 2024-03-25 00:46 UTC by LemonGrace

### Какую задачу решаем
https://linear.app/it-kotiki/issue/IK-22/sverstat-ekran-s-nachalom-igry

### Скриншоты/видяшка (если есть)
![image](https://github.com/LemonGrace/it-kotiki/assets/42918083/a32acc92-1e70-47d4-a09a-ae23e8cedb0a)

### TBD (если есть)

2024-03-25 07:45 UTC, auddax commented on packages/client/src/pages/Game/StartGamePage.tsx
> +export const StartGameTitle = styled(Title)`
А разве эти styled компоненты будут где-то еще использоваться?

2024-03-25 07:47 UTC, auddax approved these changes

2024-03-25 13:39 UTC, khedamir requested changes

2024-03-25 13:39 UTC, khedamir commented on packages/client/src/pages/Game/StartGamePage.tsx
> + * ![design](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXwBFRcXHhoeOyEhO3xTRlN8fHx8fHx8fHx8fHx8fHx8fHx
Не очень поняла зачем это здесь? Это можно убрать?

2024-03-25 14:27 UTC, khedamir approved these changes

2024-03-25 14:29 UTC, Aftors approved these changes

2024-03-26 11:28 UTC, IvanPeleshok requested changes
Добрый день

Отлично потрудились

Есть небольшие замечания, которые предлагаю поправить

Хорошего дня :)

2024-03-26 11:28 UTC, IvanPeleshok commented on packages/client/src/pages/Game/StartGamePage.tsx
> +/**
Какая смысловая нагрузка от этого комментария?

Если он нужен, то укажите причину, если нет - удаляем

2024-03-26 11:28 UTC, IvanPeleshok commented on packages/client/src/pages/Game/StartGamePage.tsx
> +const StartGameTitle = styled(Title)`
Предлагаю выносить стили в отдельный модуль, иначе поддерживать такую структуру и читать будет проблематично при росте проекта

2024-03-26 11:28 UTC, IvanPeleshok commented on packages/client/src/pages/Game/StartGamePage.tsx
> +		return <Countdown format="mm:ss" value={Date.now() + 1.5 * 60000} onFinish={() => setIsDisabled(false)} />;
Предлагаю вынести в константу `Date.now() + 1.5 * 60000`, чтобы был человекочитаемый код

2024-03-26 11:34 UTC, LemonGrace commented on packages/client/src/pages/Game/StartGamePage.tsx
> +/**
Это jsdoc документация
(при наведении будет изображение страницы, позже добавится более подробное описание)

2024-03-27 16:14 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Хорошего дня :)

2024-03-28 08:40 UTC, merged