Sprint5/ik 23
LemonGrace/it-kotiki pull request #14
Opened 2024-03-25 22:32 UTC by khedamir

### Какую задачу решаем
https://linear.app/it-kotiki/issue/IK-23/sverstat-stranicu-polzovatelya

### Скриншоты/видяшка (если есть)
![Screenshot 2024-03-26 012800](https://github.com/LemonGrace/it-kotiki/assets/23509287/24794e18-f061-4adf-b54e-84896091b9ad)
![Screenshot 2024-03-26 012927](https://github.com/LemonGrace/it-kotiki/assets/23509287/a3d53ce2-7a39-401c-8a79-04e145d5cee1)

### TBD (если есть)

2024-03-25 23:10 UTC, Aftors approved these changes

2024-03-26 06:46 UTC, auddax approved these changes

2024-03-26 08:13 UTC, LemonGrace requested changes

2024-03-26 08:13 UTC, LemonGrace commented on packages/client/src/components/Form/Form.tsx
> +							{name === EFIELD_TYPE.PASSWORD ||
лучше вынести `const PASSWORD_FIELDS = [EFIELD_TYPE.PASSWORD,  EFIELD_TYPE.OLD_PASSWORD,  EFIELD_TYPE.NEW_PASSWORD]` и делать проверку через includes

2024-03-26 08:13 UTC, LemonGrace commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +					className={activeBlock === 'preview' ? 'active' : ''}
Тут предполагалось использование компонента `Tabs` из библиотеки анта

2024-03-26 08:13 UTC, LemonGrace commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
> +					<img src={`${imgUrl}${userData.avatar}`} alt="" />
Тут предполагалось использование компонента `Avatar` из библиотеки ант

2024-03-26 08:13 UTC, LemonGrace commented on packages/client/src/utils/api/consts.ts
> +export const userUrl = 'https://ya-praktikum.tech/api/v2/user';
чтобы не дублировать начало `url` лучше вынести его в отдельную константу `const API_URL = 'https://ya-praktikum.tech/api/v2'`

2024-03-26 11:19 UTC, LemonGrace approved these changes

2024-03-26 19:03 UTC, kate-lozovaya approved these changes
👍🏻

2024-03-26 19:35 UTC, merged