IK-21 Сверстать страницу лидерборд
LemonGrace/it-kotiki pull request #16
Opened 2024-03-26 08:27 UTC by auddax

### Какую задачу решаем

https://linear.app/it-kotiki/issue/IK-21/sverstat-stranicu-liderbord

### Скриншоты/видяшка (если есть)

<img width="1798" alt="Снимок экрана 2024-03-26 в 11 14 19" src="https://github.com/LemonGrace/it-kotiki/assets/9900821/e056522f-36a6-4fac-9216-c8247dd1cc99">

### TBD (если есть)

2024-03-26 11:27 UTC, LemonGrace requested changes

2024-03-26 11:27 UTC, LemonGrace commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +const objectSorter = (data: ILeaderboardItem[], value: string, order: string) => {
Может метод сортировки вынести в utils?

2024-03-27 08:47 UTC, khedamir approved these changes

2024-03-27 16:42 UTC, auddax commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +const objectSorter = (data: ILeaderboardItem[], value: string, order: string) => {
Поправил

2024-03-27 20:06 UTC, Aftors approved these changes

2024-03-28 08:18 UTC, LemonGrace approved these changes

2024-03-28 08:19 UTC, merged