IK-25 Сверстать экран завершения игры
LemonGrace/it-kotiki pull request #18
Opened 2024-03-28 17:03 UTC by auddax

### Какую задачу решаем

https://linear.app/it-kotiki/issue/IK-25/sverstat-ekran-zaversheniya-igry

### Скриншоты/видяшка (если есть)

<img width="1798" alt="Снимок экрана 2024-03-28 в 19 57 05" src="https://github.com/LemonGrace/it-kotiki/assets/9900821/8dc24c61-85e5-4c52-9581-5752504fcaa3">

### TBD (если есть)

2024-03-28 19:12 UTC, LemonGrace approved these changes

2024-03-28 22:00 UTC, Aftors approved these changes

2024-03-28 22:01 UTC, khedamir requested changes

2024-03-28 22:01 UTC, khedamir commented on packages/client/src/components/Modal/constants/ModalConfig.tsx
> +		title: 'Игра завершена',
Привет, мне надо выводить количество убитых, после завершения игры
Добавь пожалуйста под надписью Игра завершена эту строку
При вызове модалки я буду передавать это количество через пропсы

2024-03-29 16:50 UTC, ZhannaAV approved these changes

2024-03-29 17:36 UTC, khedamir approved these changes

2024-03-29 17:44 UTC, merged