IK-35 Написать тесты на игровой движок + любой UI
LemonGrace/it-kotiki pull request #19
Opened 2024-03-29 18:48 UTC by auddax

### Какую задачу решаем

https://linear.app/it-kotiki/issue/IK-35/napisat-testy-na-igrovoj-dvizhok-lyuboj-ui

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-03-29 21:05 UTC, Aftors approved these changes
Неплохо👍🏻

2024-03-29 22:11 UTC, ZhannaAV approved these changes

2024-03-29 22:59 UTC, khedamir approved these changes

2024-03-30 04:50 UTC, LemonGrace approved these changes

2024-03-30 05:41 UTC, IvanPeleshok requested changes
Отличная работа

Есть небольшие косметические пожелания, предлагаю поправить

Хорошего дня :)

2024-03-30 05:41 UTC, IvanPeleshok commented on packages/client/src/core/findPath.test.ts
> +const expected = [
Предлагаю рядом с тестом создать mock модуль, в который можем положить необходимые для теста данные

Могут использоваться как json, так и ts / js форматы

Таким образом, вынесем всё, что мешает читать логику тестов

2024-03-30 05:41 UTC, IvanPeleshok commented on packages/client/src/pages/ForumPage/ForumPage.test.tsx
> +		Object.defineProperty(window, 'matchMedia', {
Предлагаю вынести на уровень конфигурации jest `packages/client/jest.config.js`
Так как полагаю, что данный кейс было бы здорово иметь по умолчанию для всех тестов

Добавляем к конфигурации поле
```
setupFilesAfterEnv: ['./setup-tests.ts']
```

В модуль setup-tests.ts
```
// Добавляем недостающую функцию matchMedia в объект windows
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(),
    removeListener: jest.fn(),
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});

2024-03-30 05:41 UTC, IvanPeleshok commented on packages/client/src/utils/helpers.test.ts
> +		const data = [
Давай тоже в мок данные вынесем с контекстным названием (ну и соответственно данные в других тестах тоже)

2024-03-30 10:54 UTC, IvanPeleshok approved these changes
Всё супер, апрув! 🚀

2024-03-30 11:26 UTC, merged