IK-28 Redux хранилище
LemonGrace/it-kotiki pull request #20
Opened 2024-03-29 21:58 UTC by ZhannaAV

### Какую задачу решаем
https://linear.app/it-kotiki/issue/IK-28/redux-hranilishe

### Скриншоты/видяшка (если есть)
![Снимок экрана (532)](https://github.com/LemonGrace/it-kotiki/assets/65401004/a45f65b1-f7bc-4956-8c7e-61c815b9d336)

### TBD (если есть)

2024-03-29 22:47 UTC, Aftors approved these changes
Все круто, а за notification отдельный like

2024-03-29 23:12 UTC, khedamir approved these changes
Отлично!!

2024-03-30 04:54 UTC, LemonGrace approved these changes

2024-03-30 05:05 UTC, auddax approved these changes

2024-03-30 05:58 UTC, IvanPeleshok requested changes
Отличная работа
Здорово потрудились

Есть небольшие предложения и замечания, предлагаю доработать

Хорошего дня :)

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/components/Form/Form.tsx
> +	onSubmit: (any) => Promise<void>;
any недопустимо, предлагаю `unknown`

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/components/Form/Form.tsx
> +export const Form: FC = <T,>({ type, onSubmit, initialData }: IProps<T>) => {
T, - `,` видимо лишняя

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/components/Header/Header.tsx
> +			me()
Предлагаю запросы выносить на уровень redux
Т.к вы используете redux-toolkit, то отлично бы подошёл метод createAsyncThunk https://redux-toolkit.js.org/api/createAsyncThunk
Ознакомиться можно, к примеру, тут https://www.youtube.com/watch?v=80c33x2ne20&ab_channel=codewithlari

Давайте перепишем логику запросов с прослойкой через redux, чтобы данные тянулись из одного источника
Такую систему будет проще масштабировать и тестировать

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>  		logout()
Было бы здорово вынести на уровень redux

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/pages/SignPage/SignPage.tsx
>  		return auth(AUTH_ENDPOINT[type], body)
Аналогично :)

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/store/slices/notification.slice.ts
> +interface INState {
Предлагаю не сокращать наименования, чтобы это было человекочитаемо
```
IInitialState

2024-03-30 05:58 UTC, IvanPeleshok commented on packages/client/src/store/slices/notification.slice.ts
> +interface INData {
IInitialData

2024-03-30 09:33 UTC, ZhannaAV commented on packages/client/src/components/Form/Form.tsx
> +export const Form: FC = <T,>({ type, onSubmit, initialData }: IProps<T>) => {
не лишняя, такова семантика) без неё ругается

2024-03-30 09:44 UTC, ZhannaAV commented on packages/client/src/store/slices/notification.slice.ts
> +interface INData {
заменила на INotificationData, но в целом это локальная типизация для слайса Notification и применяется только внутри createReducer метода в таком виде (state: INState, { payload }: PayloadAction<INData>). Поэтому тут это допустимо, на мой взгляд.. Для экспортируемых сущностей согласна, что лучше не сокращать)

2024-03-30 09:45 UTC, ZhannaAV commented on packages/client/src/store/slices/notification.slice.ts
> +interface INState {
заменила на INotificationState, но в целом это локальная типизация для слайса Notification и применяется только внутри createReducer метода в таком виде (state: INState, { payload }: PayloadAction<INData>). Поэтому тут это допустимо, на мой взгляд.. Для экспортируемых сущностей согласна, что лучше не сокращать)

2024-03-31 05:31 UTC, ZhannaAV commented on packages/client/src/components/Header/Header.tsx
> +			me()
Все асинхронные операции с данными юзера вынесла на уровень редакса

2024-03-31 05:35 UTC, ZhannaAV commented on packages/client/src/pages/ProfilePage/ProfilePage.tsx
>  		logout()
Авторизацию я не хочу трогать, она завязана на локальный стор. И так пришлось отрефачить много кода по юзеру, чтобы красиво легли асинхронные экшены

2024-03-31 09:30 UTC, IvanPeleshok requested changes
Отлично порефакторили

Есть небольшие предложения по улучшению фичи :)
Предлагаю доработать

Хорошего дня

2024-03-31 09:30 UTC, IvanPeleshok commented on packages/client/src/pages/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +	const uploadButton = (
Предлагаю переписать на правила в css

Подобных подход создания элементов внутри компонент не очень хорошо читается

Предлагаю вынести на уровень отдельной сущности, либо вынести в основной return jsx

2024-03-31 09:30 UTC, IvanPeleshok commented on packages/client/src/pages/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +				{avatar ? <img src={`${imgUrl}${avatar}`} alt="avatar" style={{ width: '100%' }} /> : uploadButton}
width вынести в правила

2024-03-31 09:30 UTC, IvanPeleshok commented on packages/client/src/store/slices/user.slice.ts
> +export const getUser = createAsyncThunk<IUserDTO, void, { rejectValue: string }>(
Обычно thunk-и выносят в отдельный файл (модуль)
Так файл будет проще читать и модифицировать :)

2024-03-31 09:30 UTC, IvanPeleshok commented on packages/client/src/store/slices/user.slice.ts
> +			const response = await axios.get(`${authUrl}/user`, {
Вижу, что повторяется конфигурация запросов

Предлагаю воспользоваться `axios.create`, куда вынести все необходимые конфигурации
https://axios-http.com/ru/docs/instance
Пример
```
const instance = axios.create({
  baseURL: 'https://some-domain.com/api/',
  timeout: 1000,
  headers: {'X-Custom-Header': 'foobar'}
});
```

2024-03-31 14:16 UTC, ZhannaAV commented on packages/client/src/pages/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +	const uploadButton = (
Я взяла это из библиотеки анта для быстрого рефача. Пометку в to be done по причёсыванию этого куска я сделала в описании задачи. Всё-таки у меня задача по редаксу только)

2024-03-31 14:20 UTC, ZhannaAV commented on packages/client/src/pages/ProfilePage/ProfileAvatar/ProfileAvatar.tsx
> +				{avatar ? <img src={`${imgUrl}${avatar}`} alt="avatar" style={{ width: '100%' }} /> : uploadButton}
Стили полностью переиграются. Это быстрый рефач чтобы разделить логику отправки запросов которые раньше сетились из одной формы. См. описание ПР)

2024-03-31 14:34 UTC, ZhannaAV commented on packages/client/src/store/slices/user.slice.ts
> +export const getUser = createAsyncThunk<IUserDTO, void, { rejectValue: string }>(
Вынесла

2024-03-31 14:44 UTC, ZhannaAV commented on packages/client/src/store/slices/user.slice.ts
> +			const response = await axios.get(`${authUrl}/user`, {
Интересное предложение) Но на мой взгляд это избыточная оптимизация для 4х запросов вида. У одного отличается Content-Type, поэтому это придётся прокидывать для каждого вызова инстанса. И в итоге я получу те же 3 строчки в каждом санке... 
 `
			const response = await axios.put(`${userUrl}/profile/avatar`, body, {
				withCredentials: true,
				'Content-Type': 'multipart/form-data',
			});`

2024-03-31 17:59 UTC, IvanPeleshok commented on packages/client/src/store/slices/user.slice.ts
> +			const response = await axios.get(`${authUrl}/user`, {
Это сейчас у вас 4 вызова, в дальнейшем они будут рости и это просто крутая фича для консолидации запросов

Некоторые поля можно перезаписывать, экземпляр будет содержать базовую структуру

2024-03-31 18:00 UTC, IvanPeleshok approved these changes
Апрув

Отличная работа

Ответил на комментарий про запросы

Хорошего дня :)

2024-03-31 18:23 UTC, merged