IK-18 Вёрстка страницы форума
LemonGrace/it-kotiki pull request #7
Opened 2024-03-21 17:45 UTC by auddax

### Какую задачу решаем

https://linear.app/it-kotiki/issue/IK-18/vyorstka-stranicy-foruma

### Скриншоты/видяшка (если есть)

<img width="1798" alt="314642989-84bf2b35-4dd9-462a-859b-f44b20ca9428" src="https://github.com/LemonGrace/it-kotiki/assets/9900821/24f343a8-35ee-4cb2-81e7-59d6dd94fbaa">

### TBD (если есть)

2024-03-21 18:00 UTC, khedamir approved these changes

2024-03-21 18:15 UTC, LemonGrace requested changes

2024-03-21 18:15 UTC, LemonGrace commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +		font-size: 24px;
Заголовок заложен в ui-kit, можно в `antd.config.ts` установить `fontSizeHeading1: 24,`

2024-03-21 18:15 UTC, LemonGrace commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +	&& {
Можно без обертки, сразу перечислять свойства

2024-03-21 18:15 UTC, LemonGrace commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +const ForumCard = styled(Card)`
У компонента `Card` нет исходных параметров по отступу, поэтому я бы вынесла вот эту обертку в наш компонент `IKCard`  со стилями 
```
width: 100%;
  border-radius: 24px;

  .ant-card-body {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px 24px;
    border: 1px solid;
    border-radius: 24px;
    height: 85px;
  }
```

2024-03-21 18:15 UTC, LemonGrace commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +			<div>Ответов:</div>
А почему не захотел через `Text`?

2024-03-21 19:29 UTC, auddax commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +			<div>Ответов:</div>
он же не блоковый

2024-03-21 19:33 UTC, auddax commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +const ForumCard = styled(Card)`
не понял, о каких параметрах по отступу речь?

2024-03-21 19:35 UTC, auddax commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +		font-size: 24px;
почему то  стили для Title в конфиге не срабатывают, там что-то закомментированное над каждым компонентом, может из-за этого? и что это кстати?

2024-03-22 15:15 UTC, ZhannaAV approved these changes

2024-03-22 15:15 UTC, ZhannaAV commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +	height: 430px;
я бы сделала высоту списка подлиннее, а то там ещё куча места до футера)

2024-03-22 16:02 UTC, LemonGrace commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +			<div>Ответов:</div>
я вообще в макетах представляла это как текст

2024-03-22 16:05 UTC, LemonGrace commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +const ForumCard = styled(Card)`
Исходные - https://ant.design/components/card (`Design Token`)
Название думала менять, чтобы потом кто-то не взял из основной библиотеки случайно (тут на твое усмотрение)

2024-03-22 16:06 UTC, auddax commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +			<div>Ответов:</div>
могу застилизовать, только мне кажется это уже излишним усложнением

2024-03-22 16:07 UTC, LemonGrace commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +		font-size: 24px;
Это просто скриншоты того, как выглядит элемент в формате base64 (при наведении подсвечивается)
<img width="1112" alt="image" src="https://github.com/LemonGrace/it-kotiki/assets/42918083/07f6577c-f4e7-4981-8524-9727d27e6bc0">
Этот параметр будет в разделе `token`

2024-03-22 19:14 UTC, LemonGrace approved these changes

2024-03-24 09:57 UTC, rederri commented on packages/client/src/pages/ForumPage/ForumPage.tsx
> +import { Button, Flex, Typography } from 'antd';
Пробный комментарий

2024-03-24 20:17 UTC, kyzinatra commented on packages/client/src/components/ForumTopic/ForumTopic.tsx
> +
Обычно эти компоненты выносят в файл рядом с компонентом

2024-03-24 20:19 UTC, kyzinatra commented
Отличная работа! Вопросов к ней нет, продолжайте в том же духе! Ваша работа принята, успехов в дальнейшем обучении

2024-03-25 18:14 UTC, merged